% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
  12pt,
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
    \setmainfont[]{Arial}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}
\usepackage[numbers,sort&compress]{natbib}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{caption}
\usepackage{rotating}
\usepackage{multirow}
\usepackage{mwe,tikz}
\usepackage[percent]{overpic}
\usepackage{enumitem}
\usepackage{hyperref}
\newcolumntype{P}[1]{>{\raggedright\arraybackslash}p{#1}}
\newcommand{\footerDate}{3-August-2026}
\input{header.tex}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabularx}
\usepackage{xltabular}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{RESEARCH PROTOCOL\\
\strut \\
Long-term Safety and Effectiveness of Transcatheter versus Surgical
Aortic Valve Replacement}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Version: 0.0.2}
\author{}
\date{\vspace{-2.5em}}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\section{List of Abbreviations}\label{list-of-abbreviations}

\begingroup\fontsize{8}{10}\selectfont

\begin{longtable}[t]{ll}
\toprule
 & \\
\midrule
\cellcolor{gray!10}{AS} & \cellcolor{gray!10}{Aortic stenosis}\\
AVR & Aortic valve replacement\\
\cellcolor{gray!10}{BE} & \cellcolor{gray!10}{Balloon-expandable valve}\\
CDM & Common data model\\
\cellcolor{gray!10}{CI} & \cellcolor{gray!10}{Confidence interval}\\
\addlinespace
CCI & Charlson Comorbidity Index\\
\cellcolor{gray!10}{EHR} & \cellcolor{gray!10}{Electronic health record}\\
HR & Hazard ratio\\
\cellcolor{gray!10}{HIRA} & \cellcolor{gray!10}{Health Insurance Review and Assessment Service}\\
IRB & Institutional review board\\
\addlinespace
\cellcolor{gray!10}{KM} & \cellcolor{gray!10}{Kaplan-Meier}\\
LASSO & Least absolute shrinkage and selection operator\\
\cellcolor{gray!10}{OHDSI} & \cellcolor{gray!10}{Observational Health Data Sciences and Informatics}\\
OMOP & Observational Medical Outcomes Partnership\\
\cellcolor{gray!10}{PPI} & \cellcolor{gray!10}{Permanent pacemaker insertion}\\
\addlinespace
PS & Propensity score\\
\cellcolor{gray!10}{RCT} & \cellcolor{gray!10}{Randomized controlled trial}\\
SAVR & Surgical aortic valve replacement\\
\cellcolor{gray!10}{SE} & \cellcolor{gray!10}{Self-expanding valve}\\
SMD & Standardized mean difference\\
\addlinespace
\cellcolor{gray!10}{STS} & \cellcolor{gray!10}{Society of Thoracic Surgeons}\\
TAVR & Transcatheter aortic valve replacement\\
\cellcolor{gray!10}{TCO} & \cellcolor{gray!10}{Target-comparator-outcome}\\
\bottomrule
\end{longtable}
\endgroup{}

\clearpage

\section{Responsible Parties}\label{responsible-parties}

\subsection{Investigators}\label{investigators}

\begingroup\fontsize{8}{10}\selectfont

\begin{longtable}[t]{>{\raggedright\arraybackslash}p{10em}>{\raggedright\arraybackslash}p{35em}}
\toprule
Investigator & Institution/Affiliation\\
\midrule
\cellcolor{gray!10}{Yiju Park} & \cellcolor{gray!10}{Department of Biomedical Systems Informatics, Yonsei University College of Medicine, Seoul, Korea}\\
Seung-Jun Lee & Division of Cardiology, Severance Cardiovascular Hospital, Yonsei University College of Medicine, Seoul\\
\cellcolor{gray!10}{Seng Chan You*} & \cellcolor{gray!10}{Department of Biomedical Systems Informatics, Yonsei University College of Medicine, Seoul, Korea}\\
\bottomrule
\multicolumn{2}{l}{\rule{0pt}{1em}* Principal Investigator}\\
\end{longtable}
\endgroup{}

\subsection{Disclosures}\label{disclosures}

This study is undertaken within Observational Health Data Sciences and
Informatics (OHDSI), an open collaboration.

\clearpage

\section{Abstract}\label{abstract}

\textbf{Background and Significance}: Aortic stenosis is the most
prevalent valvular heart disease in older adults, and transcatheter
aortic valve replacement (TAVR) has rapidly expanded from high-risk to
low-risk surgical patients over the past decade. While randomized
controlled trials (RCTs) have demonstrated non-inferiority of TAVR
compared with surgical aortic valve replacement (SAVR) across surgical
risk categories, these trials have limited follow-up periods and narrow
inclusion criteria. Long-term real-world comparative effectiveness data
across a broad patient population remain limited.

\textbf{Study Aims}: This study aims to compare the long-term (up to
7-year) safety and effectiveness of TAVR versus SAVR using large-scale
observational data standardized to the OMOP Common Data Model (CDM).
Additionally, the study evaluates outcomes stratified by age
(\textless80 years) and by transcatheter valve device type
(balloon-expandable versus self-expanding).

\textbf{Study Description}:

\begin{itemize}
\item
  \textbf{Population}: Adult patients with a new procedure of TAVR or
  SAVR recorded in participating observational healthcare databases,
  with at least 365 days of continuous prior observation and no prior
  aortic valve replacement.
\item
  \textbf{Comparators}: TAVR (target) versus SAVR (comparator).
  Sub-analyses include age-stratified comparisons (\textless80 years),
  device-specific comparisons (Medtronic {[}self-expanding{]} TAVR
  versus SAVR; Edwards {[}balloon-expandable{]} TAVR versus SAVR), and a
  head-to-head device comparison (Medtronic TAVR versus Edwards TAVR).
\item
  \textbf{Outcomes}: Primary outcomes are (1) composite of all-cause
  mortality or disabling stroke, and (2) reintervention. Secondary
  outcomes include all-cause mortality, disabling stroke, all stroke,
  myocardial infarction, new permanent pacemaker insertion, atrial
  fibrillation, aortic valve hospitalization, and a composite of
  all-cause mortality, disabling stroke, and aortic valve
  hospitalization.
\item
  \textbf{Design}: New-user active comparator cohort study with
  large-scale propensity score matching using the OHDSI CohortMethod
  package. Analyses are conducted across a network of observational
  healthcare databases standardized to OMOP CDM v5.4.
\item
  \textbf{Timeframe}: Six pre-specified follow-up windows are applied
  (5, 6, 7, 8, 9 years, and an intent-to-treat window with no fixed
  censoring), all bounded by a common study end date of December 31,
  2025. The primary analysis uses a 7-year maximum follow-up. Four
  propensity score adjustment methods (1:1 matching, stratification,
  IPTW, unadjusted) are applied to each time window, yielding 24
  analysis configurations per target-comparator-outcome.
\end{itemize}

\clearpage

\section{Amendments and Updates}\label{amendments-and-updates}

\begingroup\fontsize{8}{10}\selectfont

\begin{longtable}[t]{rllll}
\toprule
Number & Date & Section of study protocol & Amendment or update & Reason\\
\midrule
\cellcolor{gray!10}{1} & \cellcolor{gray!10}{2026-06-18} & \cellcolor{gray!10}{v0.01} & \cellcolor{gray!10}{} & \cellcolor{gray!10}{Initial draft}\\
2 & 2026-08-03 & v0.02 &  & update\\
\bottomrule
\end{longtable}
\endgroup{}

\section{Rationale and Background}\label{rationale-and-background}

Aortic stenosis (AS) is the most common valvular heart disease in
developed countries, affecting approximately 2--5\% of adults over the
age of 65 years and carrying a poor prognosis when left
untreated.{[}\citeproc{ref-Lung2003}{1}{]} For decades, surgical aortic
valve replacement (SAVR) was the only definitive treatment, with
well-established long-term durability. However, a substantial proportion
of patients with severe AS are at elevated surgical risk due to advanced
age and comorbidities, making SAVR high-risk or prohibitive.

Transcatheter aortic valve replacement (TAVR) was introduced as a less
invasive alternative to SAVR, first performed in humans by Cribier et
al.~in 2002.{[}\citeproc{ref-Cribier2002}{2}{]} The landmark PARTNER
trial in 2010--2011 demonstrated that TAVR was superior to medical
therapy in inoperable patients and non-inferior to SAVR in
high-surgical-risk patients, establishing TAVR as a therapeutic standard
for these
groups.{[}\citeproc{ref-Leon2010}{3},\citeproc{ref-Smith2011}{4}{]} The
CoreValve US Pivotal Trial (2014) further confirmed these findings with
self-expanding transcatheter valves.{[}\citeproc{ref-Adams2014}{5}{]}

Subsequent trials extended TAVR indications to intermediate-risk
patients. The PARTNER 2 trial (2016) demonstrated non-inferiority of
TAVR with the SAPIEN XT valve compared with SAVR in intermediate-risk
patients.{[}\citeproc{ref-Leon2016}{6}{]} The SURTAVI trial (2017)
confirmed similar findings using the CoreValve Evolut R self-expanding
valve.{[}\citeproc{ref-Reardon2017}{7}{]} These results led to expanded
regulatory approval and increased clinical adoption of TAVR across a
broader patient population.

The NOTION trial (2015) was among the first to evaluate TAVR in
lower-risk patients, showing comparable clinical outcomes between TAVR
and SAVR at 1 year in a predominantly low-risk Scandinavian
cohort.{[}\citeproc{ref-Thyregod2015}{8}{]} More definitive evidence
emerged from the PARTNER 3 trial (2019) and the Evolut Low Risk trial
(2019), which demonstrated non-inferiority---and in some endpoints
superiority---of TAVR over SAVR in low-risk patients at 1 and 2
years.{[}\citeproc{ref-Mack2019}{9},\citeproc{ref-Popma2019}{10}{]}
These pivotal results led to the approval of TAVR for low-surgical-risk
patients in 2019, effectively removing surgical risk stratification as a
prerequisite for TAVR.

Despite robust short-term RCT evidence, important knowledge gaps remain.
First, the durability of transcatheter bioprostheses over periods
exceeding 5 years is not well established in low- to intermediate-risk
patients who have longer life
expectancy.{[}\citeproc{ref-Foroutan2016}{11}{]} Second, RCTs have
narrow inclusion/exclusion criteria that limit generalizability to
real-world clinical practice, including elderly patients, those with
multiple comorbidities, and patients with complex anatomical features.
Third, specific differences between valve device types---particularly
balloon-expandable valves (BEV; Edwards SAPIEN family) and
self-expanding valves (SEV; Medtronic CoreValve/Evolut family)---in
long-term outcomes remain understudied in comparative effectiveness
research. The SEV devices are associated with higher rates of new
permanent pacemaker (PPI) implantation, while BEV devices may carry
different risks for paravalvular leak and vascular complications.

In younger patients (aged \textless80 years), the question of TAVR
versus SAVR is particularly clinically significant, because these
patients are expected to outlive the durability horizon of currently
available transcatheter bioprostheses. Current guidelines recommend
individualized decision-making in younger patients, yet evidence to
inform such decisions is
limited.{[}\citeproc{ref-Vahanian2021}{12},\citeproc{ref-Otto2021}{13}{]}

Large-scale real-world observational studies using standardized data can
complement RCT evidence by providing population-level effectiveness
estimates across diverse patient groups with longer follow-up. The OHDSI
collaborative network, with its use of the OMOP CDM, enables federated
multi-database analyses that maintain patient-level privacy while
aggregating evidence across geographically and clinically diverse
populations. Empirical calibration using negative control outcomes
addresses residual systematic error inherent to observational
designs.{[}\citeproc{ref-Schuemie2018-pnas}{14},\citeproc{ref-Schuemie2018-zi}{15}{]}

This study leverages the OHDSI Population-Level Estimation (PLE)
framework to conduct a large-scale, multi-database comparative
effectiveness study of TAVR versus SAVR with a focus on long-term
outcomes up to 7 years, with pre-specified analyses across device types
and age subgroups. The 7-year follow-up horizon is motivated by the
recent 7-year results of the Evolut Low Risk Trial, which provided the
longest available RCT-level evidence for TAVR durability in low-risk
patients.{[}\citeproc{ref-Forrest2026}{16}{]}

\section{Study Objectives}\label{study-objectives}

\subsection{Primary Objectives}\label{primary-objectives}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  To estimate the long-term (up to 7-year) risk of the composite
  endpoint of all-cause mortality or disabling stroke in patients
  undergoing TAVR compared with those undergoing SAVR.
\item
  To estimate the long-term (up to 7-year) risk of reintervention
  (valve-related reintervention) in patients undergoing TAVR compared
  with those undergoing SAVR.
\end{enumerate}

\subsection{Secondary Objectives}\label{secondary-objectives}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  To estimate the long-term risk of all-cause mortality in patients
  undergoing TAVR compared with SAVR.
\item
  To estimate the long-term risk of disabling stroke (inpatient stroke)
  in patients undergoing TAVR compared with SAVR.
\item
  To estimate the long-term risk of all stroke (inpatient and
  outpatient) in patients undergoing TAVR compared with SAVR.
\item
  To estimate the long-term risk of myocardial infarction (MI) in
  patients undergoing TAVR compared with SAVR.
\item
  To estimate the long-term risk of new permanent pacemaker insertion
  (New PPI) in patients undergoing TAVR compared with SAVR.
\item
  To estimate the long-term risk of new-onset atrial fibrillation (AF)
  in patients undergoing TAVR compared with SAVR.
\item
  To estimate the long-term risk of aortic valve hospitalization in
  patients undergoing TAVR compared with SAVR.
\item
  To estimate the long-term risk of the composite endpoint of all-cause
  mortality, disabling stroke, and aortic valve hospitalization in
  patients undergoing TAVR compared with SAVR.
\end{enumerate}

\subsection{Exploratory Objectives}\label{exploratory-objectives}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  To evaluate the above outcomes in patients aged less than 80 years at
  the time of the procedure.
\item
  To evaluate the above outcomes in patients receiving Medtronic
  (self-expanding) TAVR compared with SAVR.
\item
  To evaluate the above outcomes in patients receiving Edwards
  (balloon-expandable) TAVR compared with SAVR.
\item
  To compare outcomes between patients receiving Medtronic TAVR and
  those receiving Edwards TAVR (head-to-head device comparison).
\end{enumerate}

\section{Research Methods}\label{research-methods}

\subsection{Study Design}\label{study-design}

This is a non-interventional, retrospective, new-user active comparator
cohort study conducted across a federated network of observational
healthcare databases standardized to the OMOP CDM version 5.4. The study
is an open OHDSI network study, meaning any institution with OMOP
CDM-compliant data is invited to participate. The study adheres to the
OHDSI Population-Level Estimation (PLE) framework and uses the
CohortMethod R package for propensity score-based
analysis.{[}\citeproc{ref-Schuemie2020-fa}{17}{]}

In the new-user design, only patients initiating TAVR or SAVR for the
first time are eligible for inclusion, thereby avoiding prevalent-user
bias.{[}\citeproc{ref-Suissa2008}{18}{]} The active comparator design
(TAVR versus SAVR) reduces confounding by indication that would arise
from comparison against an untreated group, as both groups share the
indication of severe aortic stenosis requiring valve replacement.

The index date is defined as the date of the first recorded TAVR or SAVR
procedure. The time-at-risk begins on the day after the index date. To
comprehensively characterize the temporal evolution of treatment effects
and to maximize comparability with published RCT follow-up durations,
six pre-specified follow-up windows are applied: 5, 6, 7, 8, and 9
years, as well as an intent-to-treat (ITT) window with no fixed
censoring. The primary analysis uses a 7-year (2,555-day) maximum
follow-up, aligning with the Evolut Low Risk Trial 7-year
results.{[}\citeproc{ref-Forrest2026}{16}{]} All analyses share a common
study end date of December 31, 2025, which serves as an additional
censoring boundary regardless of the specified risk window.

\subsection{Data Sources}\label{data-sources}

\subsubsection{Network Study Design and Federated
Analysis}\label{network-study-design-and-federated-analysis}

This study is conducted as an OHDSI network study using a federated,
distributed analysis approach. Each participating site executes an
identical, pre-specified R study package locally on patient-level data
that never leave the institution's secure environment. Only aggregate
summary statistics (e.g., cohort counts, covariate summaries, effect
estimates, calibration diagnostics) are shared with the study
coordinator. No patient-level data are transmitted outside of
participating institutions at any time.

The study package is made publicly available through the OHDSI GitHub
repository (\url{https://github.com/ohdsi-studies}), enabling
transparent peer review of all analytical code prior to execution. Any
institution with data mapped to the OMOP CDM version 5.4 is eligible to
participate. Participation is voluntary and governed by each site's
local data governance and regulatory requirements.

\subsubsection{Anchor Data Sources}\label{anchor-data-sources}

The analyses are initially anchored at the following two Korean
databases, which represent the primary sites for which cohort
definitions and outcome concept sets have been developed and validated:

\begingroup\fontsize{8}{10}\selectfont

\begin{longtable}[t]{>{\raggedright\arraybackslash}p{10em}>{\raggedright\arraybackslash}p{5em}>{\raggedright\arraybackslash}p{9em}>{\raggedright\arraybackslash}p{10em}>{\raggedright\arraybackslash}p{8em}}
\toprule
Data Source & Country & Data Type & Population & Time Period\\
\midrule
\cellcolor{gray!10}{Health Insurance Review and Assessment Service (HIRA)} & \cellcolor{gray!10}{South Korea} & \cellcolor{gray!10}{National administrative claims} & \cellcolor{gray!10}{Entire insured population (\textasciitilde{}50 million)} & \cellcolor{gray!10}{2002<U+2013>present}\\
Severance Cardiovascular Hospital (SEV) & South Korea & Hospital EHR & Tertiary Hospital (Yonsei University Medical Center) & 2006<U+2013>present\\
\bottomrule
\end{longtable}
\endgroup{}

\textbf{Health Insurance Review and Assessment Service (HIRA)}: HIRA is
the Korean national health insurance claims database covering
approximately 97\% of the Korean population. It contains longitudinal
data on diagnoses (coded using the Korean Classification of Diseases, a
modified version of ICD-10), procedures, prescriptions, and healthcare
resource utilization for all insured individuals. The HIRA database has
been mapped to the OMOP CDM and has been used in multiple OHDSI network
studies.

\textbf{Severance Cardiovascular Hospital (SEV)}: The Severance
Cardiovascular Hospital at Yonsei University Medical Center is a
tertiary hospital in Seoul, Korea with a dedicated structural heart
disease program. Electronic health records include inpatient and
outpatient clinical data, procedural records, laboratory results, and
longitudinal follow-up. The EHR data have been mapped to the OMOP CDM
v5.4.

\subsubsection{OHDSI Network
Participation}\label{ohdsi-network-participation}

In addition to the anchor sites, this study invites participation from
any OHDSI network partner institution globally. Expanding to a broader
network of databases is intended to increase sample size, enhance
generalizability beyond the Korean healthcare context, and enable
assessment of result consistency across diverse healthcare systems,
payer structures, and geographic regions.

Institutions interested in participating should contact the study
coordinator (Seng Chan You; e-mail: {[}to be provided{]}) or express
interest through the OHDSI community forums
(\url{https://forums.ohdsi.org}). The study is registered on the OHDSI
open science initiative, and participation requires no formal agreement
beyond compliance with each site's local data use and governance
policies.

\subsubsection{Requirements for Participating
Sites}\label{requirements-for-participating-sites}

To participate in this network study, each site must meet the following
requirements:

\begingroup\fontsize{8}{10}\selectfont

\begin{longtable}[t]{>{\raggedright\arraybackslash}p{10em}>{\raggedright\arraybackslash}p{30em}}
\toprule
Requirement & Details\\
\midrule
\cellcolor{gray!10}{OMOP CDM version} & \cellcolor{gray!10}{Version 5.4}\\
Vocabulary version & OHDSI standard vocabularies (Athena); SNOMED CT required for procedure and device concepts\\
\cellcolor{gray!10}{Minimum data period} & \cellcolor{gray!10}{At least one year of continuous observation data prior to first observed TAVR or SAVR procedure in the database}\\
Concept coverage & SNOMED procedure and device concepts for aortic valve replacement must be present in the data\\
\cellcolor{gray!10}{Minimum cohort size} & \cellcolor{gray!10}{At least 50 patients in either the TAVR or SAVR cohort (sites with smaller populations are encouraged to discuss with the study coordinator)}\\
\addlinespace
Technical infrastructure & R (version 4.1 or higher) with the renv package for dependency management; database connection via DatabaseConnector\\
\cellcolor{gray!10}{Data governance} & \cellcolor{gray!10}{Local IRB waiver or approval and data use authorization as required by institutional policy}\\
\bottomrule
\end{longtable}
\endgroup{}

\subsubsection{Result Sharing and
Aggregation}\label{result-sharing-and-aggregation}

Each participating site executes the study package locally and exports a
set of pre-defined results files containing only aggregate statistics.
These files include:

\begin{itemize}
\tightlist
\item
  \textbf{Cohort attrition counts}: The number of patients at each
  inclusion step.
\item
  \textbf{Baseline covariate summaries}: Standardized mean differences
  and mean values for all covariates before and after PS adjustment.
\item
  \textbf{Propensity score diagnostics}: Preference score distributions
  and covariate balance plots.
\item
  \textbf{Outcome counts and person-time}: Event counts and person-years
  at risk for each outcome and follow-up window.
\item
  \textbf{Effect estimates}: Hazard ratios and 95\% confidence intervals
  for all analysis configurations.
\item
  \textbf{Negative and positive control estimates}: For empirical
  calibration and method evaluation.
\end{itemize}

No cell counts smaller than 5 are exported; sites are encouraged to
follow their institutional policies on minimum reportable cell size.
Results are uploaded to the study coordinator using the OhdsiSharing R
package via a secure SFTP protocol, or submitted through an alternative
agreed-upon secure file transfer method.

Meta-analytic pooling of results across sites will be performed using a
random-effects model to account for heterogeneity across databases.
Between-site heterogeneity will be reported alongside pooled estimates.

\subsection{Study Population}\label{study-population}

\subsubsection{Target and Comparator Cohort
Definitions}\label{target-and-comparator-cohort-definitions}

\textbf{Target cohort (TAVR)}: Patients with a first recorded occurrence
of a transcatheter aortic valve replacement procedure, identified using
SNOMED procedure concepts and device concepts specific to transcatheter
bioprosthetic aortic valve implantation. The index date is defined as
the date of the first qualifying procedure record. Patients are required
to have at least 365 days of continuous prior observation in the
database before the index date. Patients with a prior record of any
aortic valve replacement (TAVR or SAVR) before the index date are
excluded. The cohort end date corresponds to the end of continuous
observation.

\textbf{Comparator cohort (SAVR)}: Patients with a first recorded
occurrence of a surgical aortic valve replacement procedure, identified
using SNOMED procedure concepts for surgical replacement of the aortic
valve. The index date, washout period, prior observation requirement,
and exclusion criteria are identical to those applied to the target
cohort.

\subsubsection{Subgroup Cohort
Definitions}\label{subgroup-cohort-definitions}

\textbf{Age \textless80 subgroup}: Target and comparator cohorts
restricted to patients aged less than 80 years at the index date. This
subgroup is of particular clinical interest, as younger patients have
longer life expectancy relative to expected prosthetic valve durability,
and are more commonly considered for SAVR in contemporary guidelines.

\textbf{Device-specific TAVR cohorts}: TAVR patients are further
classified by valve device type:

\begin{itemize}
\tightlist
\item
  \emph{Medtronic TAVR} (self-expanding valve, SEV): Patients receiving
  a CoreValve, Evolut R, or Evolut PRO transcatheter valve, identified
  by Medtronic-specific device concept codes.
\item
  \emph{Edwards TAVR} (balloon-expandable valve, BEV): Patients
  receiving a SAPIEN XT, SAPIEN 3, or SAPIEN 3 Ultra transcatheter
  valve, identified by Edwards-specific device concept codes.
\end{itemize}

\subsubsection{Target-Comparator Pairs}\label{target-comparator-pairs}

\begingroup\fontsize{8}{10}\selectfont

\begin{longtable}[t]{>{\raggedright\arraybackslash}p{5em}>{\raggedright\arraybackslash}p{10em}>{\raggedright\arraybackslash}p{10em}>{\raggedright\arraybackslash}p{18em}}
\toprule
\# & Target & Comparator & Analysis Type\\
\midrule
\cellcolor{gray!10}{1 (Primary)} & \cellcolor{gray!10}{TAVR (age <80)} & \cellcolor{gray!10}{SAVR (age <80)} & \cellcolor{gray!10}{Primary comparison in younger patients}\\
2 & TAVR (all ages) & SAVR (all ages) & Overall comparison across all ages\\
\cellcolor{gray!10}{3} & \cellcolor{gray!10}{Medtronic TAVR (age <80)} & \cellcolor{gray!10}{SAVR (age <80)} & \cellcolor{gray!10}{Device-specific comparison: SEV vs. SAVR}\\
4 & Edwards TAVR (age <80) & SAVR (age <80) & Device-specific comparison: BEV vs. SAVR\\
\cellcolor{gray!10}{5} & \cellcolor{gray!10}{Medtronic TAVR (all ages)} & \cellcolor{gray!10}{Edwards TAVR (all ages)} & \cellcolor{gray!10}{Head-to-head device comparison: SEV vs. BEV}\\
\bottomrule
\end{longtable}
\endgroup{}

\subsection{Exposure Comparators}\label{exposure-comparators}

\textbf{Target exposure -- Transcatheter Aortic Valve Replacement
(TAVR)}: TAVR is a catheter-based procedure in which a bioprosthetic
valve is delivered and deployed within the native aortic valve without
open-heart surgery, most commonly via a transfemoral approach. In this
study, TAVR includes all commercially available transcatheter valve
systems regardless of access route. Device-specific sub-analyses
distinguish between self-expanding valves (Medtronic CoreValve/Evolut
family) and balloon-expandable valves (Edwards SAPIEN family).

\textbf{Comparator exposure -- Surgical Aortic Valve Replacement
(SAVR)}: SAVR involves open-heart surgery under cardiopulmonary bypass
for excision of the diseased native aortic valve and implantation of a
prosthetic valve (bioprosthetic or mechanical). In this study, SAVR
includes all surgical aortic valve replacements regardless of prosthesis
type.

\subsection{Outcomes}\label{outcomes}

All outcomes are defined as the first occurrence of the event after the
index date (day 1 or later). Outcome cohort definitions are constructed
in ATLAS and standardized to OMOP CDM concept sets.

\subsubsection{Primary Outcomes}\label{primary-outcomes}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Composite of all-cause mortality or disabling stroke}: The
  first occurrence of either all-cause mortality or disabling stroke
  (inpatient stroke) after the index date. All-cause mortality is
  identified from death records in the OMOP CDM. Disabling stroke is
  operationalized as a stroke diagnosis recorded in the context of an
  inpatient hospitalization.
\item
  \textbf{Reintervention}: Any aortic valve-related reintervention
  procedure after the index date, including repeat TAVR
  (valve-in-valve), SAVR after TAVR, balloon aortic valvuloplasty, or
  surgical revision for valve-related complications.
\end{enumerate}

\subsubsection{Secondary Outcomes}\label{secondary-outcomes}

\begingroup\fontsize{8}{10}\selectfont

\begin{longtable}[t]{>{\raggedright\arraybackslash}p{10em}>{\raggedright\arraybackslash}p{25em}>{\raggedright\arraybackslash}p{7em}}
\toprule
Outcome & Definition & Endpoint Type\\
\midrule
\cellcolor{gray!10}{All-cause mortality} & \cellcolor{gray!10}{Death from any cause recorded in the OMOP CDM death domain} & \cellcolor{gray!10}{Time-to-event}\\
Disabling stroke (inpatient stroke) & Stroke diagnosis (ischemic or hemorrhagic) recorded as a primary or secondary diagnosis during an inpatient hospitalization & Time-to-event\\
\cellcolor{gray!10}{All stroke} & \cellcolor{gray!10}{Any stroke diagnosis (ischemic or hemorrhagic) recorded in inpatient or outpatient settings} & \cellcolor{gray!10}{Time-to-event}\\
Myocardial infarction (MI) & Myocardial infarction diagnosis recorded as a primary or secondary diagnosis during an inpatient hospitalization & Time-to-event\\
\cellcolor{gray!10}{New permanent pacemaker insertion (New PPI)} & \cellcolor{gray!10}{First occurrence of a permanent pacemaker implantation procedure after the index date in patients without a prior pacemaker} & \cellcolor{gray!10}{Time-to-event}\\
\addlinespace
New-onset atrial fibrillation (AF) & First diagnosis of atrial fibrillation or atrial flutter after the index date in patients without a prior AF diagnosis & Time-to-event\\
\cellcolor{gray!10}{Aortic valve hospitalization} & \cellcolor{gray!10}{Inpatient hospitalization with a primary diagnosis related to structural aortic valve disease or valve failure} & \cellcolor{gray!10}{Time-to-event}\\
Composite: mortality + disabling stroke + aortic valve hospitalization & First occurrence of all-cause mortality or disabling stroke (inpatient) or aortic valve hospitalization & Time-to-event\\
\bottomrule
\end{longtable}
\endgroup{}

\subsubsection{Sensitivity Analysis Outcomes (Severance
Hospital-specific
Definitions)}\label{sensitivity-analysis-outcomes-severance-hospital-specific-definitions}

For analyses incorporating the Severance Hospital database,
database-specific outcome cohort definitions are used for
reintervention, new PPI, and the composite endpoint of all-cause
mortality, disabling stroke, and aortic valve hospitalization to account
for local coding practices and data availability. These sensitivity
analyses are conducted in parallel with the primary outcome analyses.

\subsection{Analysis}\label{analysis}

\subsubsection{Overview of Analytical
Design}\label{overview-of-analytical-design}

This study employs a pre-specified matrix of analyses crossing four
propensity score (PS) adjustment methods with six follow-up time
windows, resulting in 24 distinct analysis configurations per
target-comparator-outcome combination. The primary analysis is 7-year
follow-up with 1:1 PS matching (Analysis ID 19). All remaining
configurations serve as sensitivity analyses to evaluate the robustness
of findings to analytical choices. All analyses share an identical PS
model specification and covariates; they differ only in the PS
adjustment method and the maximum follow-up horizon.

\begingroup\fontsize{8}{10}\selectfont

\begin{longtable}[t]{>{\raggedright\arraybackslash}p{4em}>{\raggedright\arraybackslash}p{15em}>{\raggedright\arraybackslash}p{8em}>{\raggedright\arraybackslash}p{10em}}
\toprule
Analysis ID & Description & Risk Window End (days) & PS Method\\
\midrule
\cellcolor{gray!10}{1} & \cellcolor{gray!10}{Five-year outcome, one-to-one matching} & \cellcolor{gray!10}{1825 (5 years)} & \cellcolor{gray!10}{1:1 PS matching}\\
2 & Five-year outcome, stratification & 1825 (5 years) & PS stratification (5 strata)\\
\cellcolor{gray!10}{4} & \cellcolor{gray!10}{Five-year outcome, IPTW} & \cellcolor{gray!10}{1825 (5 years)} & \cellcolor{gray!10}{IPTW}\\
5 & Five-year outcome, without matching & 1825 (5 years) & Unadjusted (no PS)\\
\cellcolor{gray!10}{10} & \cellcolor{gray!10}{Six-year outcome, one-to-one matching} & \cellcolor{gray!10}{2190 (6 years)} & \cellcolor{gray!10}{1:1 PS matching}\\
\addlinespace
11 & Six-year outcome, stratification & 2190 (6 years) & PS stratification (5 strata)\\
\cellcolor{gray!10}{13} & \cellcolor{gray!10}{Six-year outcome, IPTW} & \cellcolor{gray!10}{2190 (6 years)} & \cellcolor{gray!10}{IPTW}\\
14 & Six-year outcome, without matching & 2190 (6 years) & Unadjusted (no PS)\\
\cellcolor{gray!10}{\textbf{**19**}} & \cellcolor{gray!10}{\textbf{**Seven-year outcome, one-to-one matching (PRIMARY)**}} & \cellcolor{gray!10}{\textbf{**2555 (7 years)**}} & \cellcolor{gray!10}{\textbf{**1:1 PS matching**}}\\
20 & Seven-year outcome, stratification & 2555 (7 years) & PS stratification (5 strata)\\
\addlinespace
\cellcolor{gray!10}{22} & \cellcolor{gray!10}{Seven-year outcome, IPTW} & \cellcolor{gray!10}{2555 (7 years)} & \cellcolor{gray!10}{IPTW}\\
23 & Seven-year outcome, without matching & 2555 (7 years) & Unadjusted (no PS)\\
\cellcolor{gray!10}{28} & \cellcolor{gray!10}{Eight-year outcome, one-to-one matching} & \cellcolor{gray!10}{2920 (8 years)} & \cellcolor{gray!10}{1:1 PS matching}\\
29 & Eight-year outcome, stratification & 2920 (8 years) & PS stratification (5 strata)\\
\cellcolor{gray!10}{31} & \cellcolor{gray!10}{Eight-year outcome, IPTW} & \cellcolor{gray!10}{2920 (8 years)} & \cellcolor{gray!10}{IPTW}\\
\addlinespace
32 & Eight-year outcome, without matching & 2920 (8 years) & Unadjusted (no PS)\\
\cellcolor{gray!10}{37} & \cellcolor{gray!10}{Nine-year outcome, one-to-one matching} & \cellcolor{gray!10}{3285 (9 years)} & \cellcolor{gray!10}{1:1 PS matching}\\
38 & Nine-year outcome, stratification & 3285 (9 years) & PS stratification (5 strata)\\
\cellcolor{gray!10}{40} & \cellcolor{gray!10}{Nine-year outcome, IPTW} & \cellcolor{gray!10}{3285 (9 years)} & \cellcolor{gray!10}{IPTW}\\
41 & Nine-year outcome, without matching & 3285 (9 years) & Unadjusted (no PS)\\
\addlinespace
\cellcolor{gray!10}{46} & \cellcolor{gray!10}{ITT, one-to-one matching} & \cellcolor{gray!10}{Until end of observation} & \cellcolor{gray!10}{1:1 PS matching}\\
47 & ITT, stratification & Until end of observation & PS stratification (5 strata)\\
\cellcolor{gray!10}{49} & \cellcolor{gray!10}{ITT, IPTW} & \cellcolor{gray!10}{Until end of observation} & \cellcolor{gray!10}{IPTW}\\
50 & ITT, without matching & Until end of observation & Unadjusted (no PS)\\
\bottomrule
\end{longtable}
\endgroup{}

All analyses share a common study end date of December 31, 2025. Actual
patient follow-up is thus bounded by the minimum of the risk window end,
the study end date, or the patient's last available observation period.
The ITT analyses (IDs 46--50) impose no artificial censoring at a fixed
number of days; patients are followed until end of their observation
period or the study end date.

\subsubsection{Propensity Score
Estimation}\label{propensity-score-estimation}

A propensity score (PS) is estimated for each target-comparator pair
using a large-scale regularized logistic regression model implemented
via the Cyclops R package with a Laplace (L1) prior and cross-validation
for hyperparameter selection.{[}\citeproc{ref-Suchard2013}{19}{]} The PS
model predicts the probability of receiving TAVR (versus SAVR) given a
large set of pre-index covariates.

The following covariate types are included in the PS model:

\begin{itemize}
\tightlist
\item
  \textbf{Demographics}: age (in 5-year age groups), sex, index calendar
  year, index calendar month
\item
  \textbf{Condition eras}: all recorded diagnoses in the 365-day
  (long-term) and 180-day (medium-term) windows prior to the index date
\item
  \textbf{Drug eras}: all drug exposures at the ingredient and drug
  class levels in the 365-day (long-term) and 180-day (medium-term)
  windows prior to the index date
\item
  \textbf{Procedure occurrences}: all recorded procedures in the 365-day
  and 180-day windows prior to the index date
\item
  \textbf{Device exposures}: all recorded device exposures in the
  365-day window prior to the index date
\item
  \textbf{Measurement values}: all recorded measurements in the 365-day
  window prior to the index date
\item
  \textbf{Observation records}: all observations recorded in the 365-day
  and 180-day windows prior to the index date
\item
  \textbf{Visit context}: inpatient, outpatient, and emergency visit
  counts in the 365-day window prior to the index date
\item
  \textbf{Clinical indices}: Charlson Comorbidity Index (CCI),
  CHADS\textsubscript{2} score, and Diabetes Complication Severity Index
  (DCSI) computed from the prior observation period
\end{itemize}

The following concept IDs are excluded from the PS model as they are
direct proxies of the treatment choice (aortic valve procedures and
device concepts): SNOMED concepts related to aortic valve replacement,
transcatheter valve devices, and bioprosthetic aortic valve materials
(n=15 excluded concept IDs per target-comparator pair).

\subsubsection{Propensity Score Adjustment
Methods}\label{propensity-score-adjustment-methods}

Four PS adjustment methods are applied in parallel to evaluate the
robustness of findings:

\textbf{1. One-to-one (1:1) PS matching} (primary): Patients are matched
1:1 using nearest-neighbor matching on the logit of the PS without
replacement, with a caliper of 0.2 standard deviations of the logit
PS.{[}\citeproc{ref-Austin2011}{20}{]} The matching is performed within
each target-comparator-database stratum. A stratified Cox proportional
hazards model (unstratified; treating matched pairs as independent) is
used for the outcome analysis.

\textbf{2. PS stratification}: Patients are stratified into 5 equally
sized PS strata based on the quintiles of the PS distribution. A
stratified Cox proportional hazards model, accounting for the PS strata,
is used for the outcome analysis.

\textbf{3. Inverse probability of treatment weighting (IPTW)}: Patients
are weighted by the inverse of their estimated PS (stabilized weights).
The outcome model is a Cox proportional hazards model applied to the
IPTW-weighted cohort.

\textbf{4. Unadjusted (no PS adjustment)}: No PS adjustment is applied.
The outcome model is an unadjusted Cox proportional hazards model. This
analysis provides a reference estimate to quantify the degree of
confounding addressed by the PS-based approaches.

\subsubsection{Follow-up Time Windows}\label{follow-up-time-windows}

Six follow-up horizons are pre-specified to characterize the temporal
evolution of treatment effects and to enable comparison with published
RCT follow-up durations:

\begin{itemize}
\tightlist
\item
  \textbf{5 years (1,825 days)}: Corresponds to the follow-up horizon of
  the PARTNER 3 5-year results.
\item
  \textbf{6 years (2,190 days)}: Intermediate window capturing emerging
  differences in valve durability.
\item
  \textbf{7 years (2,555 days)} \emph{(primary)}: Aligns with the 7-year
  follow-up of the Evolut Low Risk Trial (JACC,
  2026).{[}\citeproc{ref-Forrest2026}{16}{]}
\item
  \textbf{8 years (2,920 days)}: Sensitivity window for patients with
  the longest available follow-up.
\item
  \textbf{9 years (3,285 days)}: Sensitivity window for the earliest
  TAVR patients in the database.
\item
  \textbf{ITT (intent-to-treat, no fixed censoring)}: Patients followed
  until end of observation period or December 31, 2025, without
  truncation at a fixed number of days, capturing all available
  follow-up time.
\end{itemize}

\subsubsection{Covariate Balance
Assessment}\label{covariate-balance-assessment}

Covariate balance is assessed before and after PS adjustment using the
standardized mean difference (SMD) for all pre-specified covariates. An
SMD of less than 0.1 is considered indicative of adequate balance. The
distribution of PS in the target and comparator groups before and after
matching is visualized using preference score plots.

\subsubsection{Outcome Analysis}\label{outcome-analysis}

For each analysis configuration, a Cox proportional hazards model is
fitted to estimate the hazard ratio (HR) with 95\% confidence interval
(CI). The model specification (stratified or unstratified) varies by PS
adjustment method as described above. Kaplan-Meier (KM) survival curves
are generated for the primary analysis (7-year, 1:1 matching) to
visualize cumulative incidence over the follow-up period. The
time-at-risk begins on the day after the index date (day 1) to avoid
immortal time bias.

\subsubsection{Empirical Calibration}\label{empirical-calibration}

To assess and adjust for residual systematic error (unmeasured
confounding, measurement error, and other sources of bias), a set of
negative control outcomes is included in each
analysis.{[}\citeproc{ref-Schuemie2018-pnas}{14}{]} Negative controls
are conditions with no known causal relationship to TAVR or SAVR (e.g.,
dental caries, cataract, allergic rhinitis). Approximately 65 negative
control outcomes are included per target-comparator pair (see Appendix
@ref(negative-control-concepts)). The distribution of HR estimates for
negative controls is used to characterize the residual bias and estimate
empirically calibrated p-values and confidence intervals.

\subsubsection{Positive Control
Synthesis}\label{positive-control-synthesis}

Synthetic positive controls are generated by outcome model injection to
evaluate the operating characteristics of the study
design.{[}\citeproc{ref-Schuemie2018-zi}{15}{]} Positive controls with
true effect sizes of 1.5, 2.0, and 4.0 are synthesized using a survival
model. A minimum of 50 outcomes per positive control is required for
model fitting, and a minimum of 25 outcomes is required for injection.
Up to 250,000 subjects are used in the positive control synthesis model.

\subsubsection{Multiple Comparisons}\label{multiple-comparisons}

This study involves multiple target-comparator-outcome combinations
crossed with 24 analysis configurations. Results are presented for all
pre-specified analysis configurations with both uncalibrated and
empirically calibrated effect estimates. No formal Bonferroni-type
correction for multiple comparisons is applied; the primary inference is
drawn from the 7-year, 1:1 matching analysis, and the full set of
sensitivity results is made available for interpretation by the
scientific community.

\section{Sample Size and Study Power}\label{sample-size}

This is a large-scale observational network study, and no formal a
priori power calculation is conducted. The study leverages the large
populations available in the participating databases (HIRA covers the
entire Korean insured population of approximately 50 million) and
multi-database aggregation to provide sufficient statistical power for
estimating treatment effects. Given that TAVR procedures have been
performed in South Korea since the early 2010s and SAVR is a high-volume
procedure, the expected sample size in the HIRA database alone is
expected to provide tens of thousands of TAVR and SAVR patients over the
study period.

For the primary comparison (TAVR \textless80 vs.~SAVR \textless80), the
minimum detectable relative risk assuming 7-year event rates of 15--25\%
for the composite primary endpoint is expected to be in the range of
0.85--1.15, providing adequate power to detect clinically meaningful
differences.

The actual sample sizes and event counts in each database will be
reported in the results, along with minimum detectable relative risk
estimates.

\section{Strengths and Limitations}\label{strengths-limitations}

\subsection{Strengths}\label{strengths}

\begin{itemize}
\tightlist
\item
  \textbf{Large-scale real-world evidence}: The inclusion of a national
  health insurance database (HIRA) provides access to the entire insured
  Korean population, yielding a very large sample size that
  substantially increases statistical power compared with single-center
  or registry-based studies.
\item
  \textbf{Multi-database and multi-national approach}: Anchored in two
  complementary Korean databases (national claims and hospital EHR), the
  study is open to any OHDSI network site worldwide. Participation of
  international sites with different healthcare systems, payer
  structures, and TAVR adoption timelines will strengthen external
  validity, enable cross-national comparison, and increase the total
  sample size---particularly for low-frequency outcomes and
  device-specific subgroup analyses.
\item
  \textbf{New-user active comparator design}: The new-user design avoids
  prevalent-user bias, and the active comparator design (SAVR as
  comparator rather than untreated) reduces confounding by indication
  and severity.
\item
  \textbf{Large-scale propensity score adjustment}: The large-scale PS
  model incorporating hundreds to thousands of covariates enables
  adjustment for a wide range of potential confounders, including
  comorbidities, co-medications, and prior healthcare utilization
  patterns.
\item
  \textbf{Long and multiple follow-up windows}: Follow-up windows of 5,
  6, 7, 8, and 9 years, plus an ITT window, characterize the temporal
  trajectory of treatment effects and allow direct comparison with each
  major RCT follow-up duration. The 7-year primary window aligns with
  the recently reported Evolut Low Risk Trial 7-year
  outcomes.{[}\citeproc{ref-Forrest2026}{16}{]}
\item
  \textbf{Multiple PS adjustment methods}: Running all four PS
  adjustment approaches (1:1 matching, stratification, IPTW, unadjusted)
  in parallel allows for evaluation of method-specific sensitivity and
  strengthens causal inference when results are consistent across
  approaches.
\item
  \textbf{Empirical calibration}: The use of negative control outcomes
  to empirically calibrate effect estimates provides a principled
  approach to detecting and correcting for residual systematic error, a
  key methodological strength of the OHDSI framework.
\item
  \textbf{Device-specific analysis}: Pre-specified sub-analyses
  comparing SEV (Medtronic) and BEV (Edwards) devices against SAVR and
  each other provide actionable comparative data for device selection.
\item
  \textbf{OMOP CDM standardization}: The use of OMOP CDM v5.4 ensures
  reproducibility, facilitates external validation, and supports future
  replication across additional OHDSI sites.
\end{itemize}

\subsection{Limitations}\label{limitations}

\begin{itemize}
\tightlist
\item
  \textbf{Residual confounding}: Despite large-scale PS matching,
  unmeasured confounders---particularly surgical risk scores (STS score,
  EuroSCORE II), echocardiographic parameters (aortic valve area, mean
  gradient, LVEF), anatomical factors (aortic root geometry, vascular
  access), and physician judgment---cannot be adjusted for in
  administrative claims data. Patients selected for TAVR versus SAVR may
  differ in ways not fully captured by the available covariates.
\item
  \textbf{Indication bias and temporal trends}: TAVR was initially
  restricted to high-risk or inoperable patients and progressively
  expanded to lower-risk patients over the study period. This secular
  trend may introduce residual confounding by indication that is
  difficult to fully eliminate with PS methods, particularly in analyses
  spanning extended calendar time periods.
\item
  \textbf{Coding variability}: Diagnosis and procedure coding practices
  may vary across data sources, time periods, and healthcare settings,
  potentially affecting outcome ascertainment and cohort identification.
\item
  \textbf{Incomplete device-specific data}: Device-specific information
  (manufacturer, model, size) may not be consistently captured in
  administrative claims data, potentially limiting the accuracy of
  device-stratified analyses in the HIRA database.
\item
  \textbf{Generalizability within Korea}: Findings from the Korean
  healthcare system may reflect Korean-specific patient demographics,
  clinical practice patterns, device availability, and insurance
  coverage policies that differ from other countries.
\item
  \textbf{Heterogeneity across network sites}: If additional OHDSI
  network sites contribute data, systematic heterogeneity in coding
  practices, patient case mix, healthcare delivery systems, and TAVR
  adoption timelines across countries may limit the interpretability of
  pooled estimates. Between-site heterogeneity will be formally assessed
  and reported.
\item
  \textbf{Concept coverage at external sites}: Participating sites
  outside Korea may use different local coding systems (e.g.,
  ICD-10-PCS, OPCS-4) that may not map uniformly to the SNOMED procedure
  and device concepts used to define TAVR and SAVR cohorts. Sites are
  encouraged to validate concept coverage prior to execution.
\item
  \textbf{Mortality ascertainment}: In claims databases, all-cause
  mortality may be incompletely captured if patients die outside of a
  healthcare setting or if death records are not linked to the claims
  database.
\item
  \textbf{Competing risks}: The analysis uses traditional time-to-event
  methods (Cox PH and KM) without formal competing risk adjustment. In a
  population with high background mortality risk (older adults
  undergoing valve replacement), competing risks may influence the
  interpretation of cause-specific event rates.
\end{itemize}

\section{Protection of Human
Subjects}\label{protection-of-human-subjects}

The study uses only de-identified or pseudonymized electronic health
record and claims data. Patient-level data are never shared across
institutions. Each participating site executes the study package locally
within its own secure data environment, and only pre-specified aggregate
statistics are transmitted to the study coordinator. Confidentiality of
patient records will be maintained at all times. All study reports will
contain aggregate data only and will not identify individual patients or
physicians.

Each participating institution is responsible for obtaining any required
local ethics committee or institutional review board (IRB) approval,
data use authorization, or waiver of informed consent in accordance with
applicable national and institutional regulations. Because the study
uses retrospective observational data without direct patient contact or
intervention, many participating sites may be eligible for an expedited
review or waiver of informed consent. Sites are asked to document and
provide evidence of their local regulatory approval to the study
coordinator prior to result submission.

\section{Management and Reporting of Adverse Events and Adverse
Reactions}\label{management-and-reporting-of-adverse-events-and-adverse-reactions}

This is a non-interventional, retrospective observational study using
existing electronic health records. No investigational products are
administered and no direct patient interventions are performed.
Accordingly, formal adverse event monitoring and reporting procedures
applicable to interventional studies are not required. Any incidental
findings of clinical significance identified during data analysis will
be handled in accordance with applicable institutional policies.

\section{Plans for Disseminating and Communicating Study
Results}\label{plans-for-disseminating-and-communicating-study-results}

Following completion of data collection and analysis across all
participating sites, results will be aggregated by the study coordinator
and made publicly available on the OHDSI website
(\url{https://www.ohdsi.org/research/ongoing-research}) and through the
OHDSI Evidence Explorer Shiny application, enabling open inspection of
results from all contributing databases. All analytical code will remain
publicly available on the OHDSI GitHub repository throughout the study.

At least one manuscript describing the study design, methods, and
results will be written and submitted for publication to a peer-reviewed
scientific journal. Authorship will follow the ICMJE guidelines; all
site investigators who contribute data and fulfill ICMJE authorship
criteria will be eligible for authorship or acknowledgment. The study
protocol will be registered and made publicly available prior to
initiation of any data analyses, in keeping with OHDSI open science
principles.

\clearpage

\section*{References}\label{references}
\addcontentsline{toc}{section}{References}

\phantomsection\label{refs}
\begin{CSLReferences}{0}{1}
\bibitem[\citeproctext]{ref-Lung2003}
\CSLLeftMargin{1 }%
\CSLRightInline{Lung B, Baron G, Butchart EG, \emph{et al.} A
prospective survey of patients with valvular heart disease in {Europe}:
The {Euro} {Heart} {Survey} on {Valvular} {Heart} {Disease}.
\emph{European Heart Journal} 2003;\textbf{24}:1231--43.
doi:\href{https://doi.org/10.1016/s0195-668x(03)00201-x}{10.1016/s0195-668x(03)00201-x}}

\bibitem[\citeproctext]{ref-Cribier2002}
\CSLLeftMargin{2 }%
\CSLRightInline{Cribier A, Eltchaninoff H, Bash A, \emph{et al.}
Percutaneous transcatheter implantation of an aortic valve prosthesis
for calcific aortic stenosis: First human case description.
\emph{Circulation} 2002;\textbf{106}:3006--8.
doi:\href{https://doi.org/10.1161/01.cir.0000047200.36165.b8}{10.1161/01.cir.0000047200.36165.b8}}

\bibitem[\citeproctext]{ref-Leon2010}
\CSLLeftMargin{3 }%
\CSLRightInline{Leon MB, Smith CR, Mack M, \emph{et al.} Transcatheter
aortic-valve implantation for aortic stenosis in patients who cannot
undergo surgery. \emph{The New England Journal of Medicine}
2010;\textbf{363}:1597--607.
doi:\href{https://doi.org/10.1056/NEJMoa1008232}{10.1056/NEJMoa1008232}}

\bibitem[\citeproctext]{ref-Smith2011}
\CSLLeftMargin{4 }%
\CSLRightInline{Smith CR, Leon MB, Mack MJ, \emph{et al.} Transcatheter
versus surgical aortic-valve replacement in high-risk patients.
\emph{The New England Journal of Medicine} 2011;\textbf{364}:2187--98.
doi:\href{https://doi.org/10.1056/NEJMoa1104610}{10.1056/NEJMoa1104610}}

\bibitem[\citeproctext]{ref-Adams2014}
\CSLLeftMargin{5 }%
\CSLRightInline{Adams DH, Popma JJ, Reardon MJ, \emph{et al.}
Transcatheter aortic-valve replacement with a self-expanding prosthesis.
\emph{The New England Journal of Medicine} 2014;\textbf{370}:1790--8.
doi:\href{https://doi.org/10.1056/NEJMoa1400590}{10.1056/NEJMoa1400590}}

\bibitem[\citeproctext]{ref-Leon2016}
\CSLLeftMargin{6 }%
\CSLRightInline{Leon MB, Smith CR, Mack MJ, \emph{et al.} Transcatheter
or surgical aortic-valve replacement in intermediate-risk patients.
\emph{The New England Journal of Medicine} 2016;\textbf{374}:1609--20.
doi:\href{https://doi.org/10.1056/NEJMoa1514616}{10.1056/NEJMoa1514616}}

\bibitem[\citeproctext]{ref-Reardon2017}
\CSLLeftMargin{7 }%
\CSLRightInline{Reardon MJ, Van Mieghem NM, Popma JJ, \emph{et al.}
Surgical or transcatheter aortic-valve replacement in intermediate-risk
patients. \emph{The New England Journal of Medicine}
2017;\textbf{376}:1321--31.
doi:\href{https://doi.org/10.1056/NEJMoa1700456}{10.1056/NEJMoa1700456}}

\bibitem[\citeproctext]{ref-Thyregod2015}
\CSLLeftMargin{8 }%
\CSLRightInline{Thyregod HG, Steinbruchel DA, Ihlemann N, \emph{et al.}
Transcatheter versus surgical aortic valve replacement in patients with
severe aortic valve stenosis: 1-year results from the all-comers
{NOTION} randomized clinical trial. \emph{Journal of the American
College of Cardiology} 2015;\textbf{65}:2184--94.
doi:\href{https://doi.org/10.1016/j.jacc.2015.03.014}{10.1016/j.jacc.2015.03.014}}

\bibitem[\citeproctext]{ref-Mack2019}
\CSLLeftMargin{9 }%
\CSLRightInline{Mack MJ, Leon MB, Thourani VH, \emph{et al.}
Transcatheter aortic-valve replacement with a balloon-expandable valve
in low-risk patients. \emph{The New England Journal of Medicine}
2019;\textbf{380}:1695--705.
doi:\href{https://doi.org/10.1056/NEJMoa1814052}{10.1056/NEJMoa1814052}}

\bibitem[\citeproctext]{ref-Popma2019}
\CSLLeftMargin{10 }%
\CSLRightInline{Popma JJ, Deeb GM, Yakubov SJ, \emph{et al.}
Transcatheter aortic-valve replacement with a self-expanding valve in
low-risk patients. \emph{The New England Journal of Medicine}
2019;\textbf{380}:1706--15.
doi:\href{https://doi.org/10.1056/NEJMoa1816885}{10.1056/NEJMoa1816885}}

\bibitem[\citeproctext]{ref-Foroutan2016}
\CSLLeftMargin{11 }%
\CSLRightInline{Foroutan F, Guyatt GH, O'Brien K, \emph{et al.}
Prognosis after surgical replacement with a bioprosthetic aortic valve
in patients with severe symptomatic aortic stenosis: Systematic review
of observational studies. \emph{BMJ} 2016;\textbf{354}:i5065.
doi:\href{https://doi.org/10.1136/bmj.i5065}{10.1136/bmj.i5065}}

\bibitem[\citeproctext]{ref-Vahanian2021}
\CSLLeftMargin{12 }%
\CSLRightInline{Vahanian A, Beyersdorf F, Praz F, \emph{et al.} 2021
{ESC}/{EACTS} guidelines for the management of valvular heart disease.
\emph{European Heart Journal} 2022;\textbf{43}:561--632.
doi:\href{https://doi.org/10.1093/eurheartj/ehab395}{10.1093/eurheartj/ehab395}}

\bibitem[\citeproctext]{ref-Otto2021}
\CSLLeftMargin{13 }%
\CSLRightInline{Otto CM, Nishimura RA, Bonow RO, \emph{et al.} 2020
{ACC}/{AHA} guideline for the management of patients with valvular heart
disease: A report of the {American} {College} of {Cardiology}/{American}
{Heart} {Association} joint committee on clinical practice guidelines.
\emph{Circulation} 2021;\textbf{143}:e72--227.
doi:\href{https://doi.org/10.1161/CIR.0000000000000923}{10.1161/CIR.0000000000000923}}

\bibitem[\citeproctext]{ref-Schuemie2018-pnas}
\CSLLeftMargin{14 }%
\CSLRightInline{Schuemie MJ, Ryan PB, Hripcsak G, \emph{et al.}
Empirical confidence interval calibration for population-level effect
estimation studies in observational healthcare data. \emph{Proceedings
of the National Academy of Sciences of the United States of America}
2018;\textbf{115}:2571--7.
doi:\href{https://doi.org/10.1073/pnas.1708282114}{10.1073/pnas.1708282114}}

\bibitem[\citeproctext]{ref-Schuemie2018-zi}
\CSLLeftMargin{15 }%
\CSLRightInline{Schuemie MJ, Ryan PB, Hripcsak G, \emph{et al.}
Improving reproducibility by using high-throughput observational studies
with empirical calibration. \emph{Philosophical Transactions Series A,
Mathematical, Physical, and Engineering Sciences} 2018;\textbf{376}.}

\bibitem[\citeproctext]{ref-Forrest2026}
\CSLLeftMargin{16 }%
\CSLRightInline{Forrest JK DG Yakubov SJ. Six-year outcomes after
transcatheter vs surgical aortic valve replacement in low-risk patients
with aortic stenosis. \emph{Journal of the American College of
Cardiology} Published Online First: 2026.
doi:\href{https://doi.org/10.1016/j.jacc.2026.02.5063}{10.1016/j.jacc.2026.02.5063}}

\bibitem[\citeproctext]{ref-Schuemie2020-fa}
\CSLLeftMargin{17 }%
\CSLRightInline{Schuemie M, Suchard M, Ryan P. {CohortMethod}: New-user
cohort method with large scale propensity and outcome models. 2020.}

\bibitem[\citeproctext]{ref-Suissa2008}
\CSLLeftMargin{18 }%
\CSLRightInline{Suissa S. Immortal time bias in pharmaco-epidemiology.
\emph{American Journal of Epidemiology} 2008;\textbf{167}:492--9.
doi:\href{https://doi.org/10.1093/aje/kwm324}{10.1093/aje/kwm324}}

\bibitem[\citeproctext]{ref-Suchard2013}
\CSLLeftMargin{19 }%
\CSLRightInline{Suchard MA, Simpson SE, Zorych I, \emph{et al.} Massive
parallelization of serial inference algorithms for a complex generalized
linear model. \emph{ACM Transactions on Modeling and Computer
Simulation} 2013;\textbf{23}:1--17.
doi:\href{https://doi.org/10.1145/2414416.2414791}{10.1145/2414416.2414791}}

\bibitem[\citeproctext]{ref-Austin2011}
\CSLLeftMargin{20 }%
\CSLRightInline{Austin PC. Optimal caliper widths for propensity-score
matching when estimating differences in means and differences in
proportions in observational studies. \emph{Pharmaceutical Statistics}
2011;\textbf{10}:150--61.
doi:\href{https://doi.org/10.1002/pst.433}{10.1002/pst.433}}

\end{CSLReferences}

\clearpage

\centerline{\Huge Appendix}

\section*{(APPENDIX) Appendix}\label{appendix-appendix}
\addcontentsline{toc}{section}{(APPENDIX) Appendix}

\section{Exposure Cohort Definitions}\label{exposure-cohort-definitions}

\begin{verbatim}
## pandoc_to(): latex
\end{verbatim}

\begin{verbatim}
## is_latex_output(): TRUE
\end{verbatim}

\begin{verbatim}
## is_html_output(): FALSE
\end{verbatim}

\subsection{Transcatheter Aortic Valve Replacement (Target, ATLAS ID:
900)}\label{transcatheter-aortic-valve-replacement-target-atlas-id-900}

\subsubsection{Cohort Entry Events}\label{cohort-entry-events}

People may enter the cohort when observing any of the following:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  condition occurrences of `{[}26HIRAMDV{]} Aortic Stenosis'.
\end{enumerate}

Limit cohort entry events to the earliest event per person.

Restrict entry events to having at least 1 device exposure of
`{[}26HIRAMDV{]} TAVR(total)', starting between 0 days before and all
days after cohort entry start date; allow events outside observation
period; starting on or after 1월 1, 2016.

\subsubsection{Additional Inclusion
Criteria}\label{additional-inclusion-criteria}

\paragraph*{I. aged more than 65}\label{i.-aged-more-than-65}
\addcontentsline{toc}{paragraph}{I. aged more than 65}

Entry events with the following event criteria: who are \textgreater= 65
years old. \#\#\#\# II. No high risk patient \{-\}

Entry events having no condition occurrences of `{[}26HIRAMDV{]} High
risk patient', starting anytime up to 7 days before cohort entry start
date; allow events outside observation period.

\paragraph*{III. No prior disorder of
heart}\label{iii.-no-prior-disorder-of-heart}
\addcontentsline{toc}{paragraph}{III. No prior disorder of heart}

Entry events having no condition occurrences of `{[}26HIRAMDV{]}
Disorder of another valve', starting anytime on or before cohort entry
start date; allow events outside observation period.

\subsubsection{Cohort Exit}\label{cohort-exit}

The person also exists the cohort at the end of continuous observation.

\subsubsection{Cohort Eras}\label{cohort-eras}

Remaining events will be combined into cohort eras if they are within 0
days of each other.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{Surgical Aortic Valve Replacement (Comparator, ATLAS ID:
902)}\label{surgical-aortic-valve-replacement-comparator-atlas-id-902}

\subsubsection{Cohort Entry Events}\label{cohort-entry-events-1}

People may enter the cohort when observing any of the following:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  condition occurrences of `{[}26HIRAMDV{]} Aortic Stenosis'.
\end{enumerate}

Limit cohort entry events to the earliest event per person.

Restrict entry events to having at least 1 procedure occurrence of
`{[}26HIRAMDV{]} SAVR', starting between 0 days before and all days
after cohort entry start date; starting on or after 1월 1, 2016.

\subsubsection{Additional Inclusion
Criteria}\label{additional-inclusion-criteria-1}

\paragraph*{I. aged more than 18}\label{i.-aged-more-than-18}
\addcontentsline{toc}{paragraph}{I. aged more than 18}

Entry events with the following event criteria: who are \textgreater= 18
years old. \#\#\#\# II. No prior complex SAVR \{-\}

Entry events having no procedure occurrences of `{[}26HIRAMDV{]}
SAVR-complex surgery', starting anytime on or before cohort entry start
date; allow events outside observation period.

\paragraph*{III. No prior
sutureless,mechanical,TAVR}\label{iii.-no-prior-suturelessmechanicaltavr}
\addcontentsline{toc}{paragraph}{III. No prior
sutureless,mechanical,TAVR}

Entry events having no procedure occurrences of `{[}26HIRAMDV{]}
SAVR-sutureless,tavr,mechanical', starting anytime on or before cohort
entry start date; allow events outside observation period.

\paragraph*{IV. No prior
reintervention}\label{iv.-no-prior-reintervention}
\addcontentsline{toc}{paragraph}{IV. No prior reintervention}

Entry events having no procedure occurrences of `{[}26HIRAMDV{]}
SAVR-reintervention', starting anytime up to 7 days before cohort entry
start date; allow events outside observation period.

\paragraph*{V. No high risk patient}\label{v.-no-high-risk-patient}
\addcontentsline{toc}{paragraph}{V. No high risk patient}

Entry events having no condition occurrences of `{[}26HIRAMDV{]} High
risk patient', starting anytime up to 7 days before cohort entry start
date; allow events outside observation period.

\paragraph*{VI. No prior disorder of
heart}\label{vi.-no-prior-disorder-of-heart}
\addcontentsline{toc}{paragraph}{VI. No prior disorder of heart}

Entry events having no condition occurrences of `{[}26HIRAMDV{]}
Disorder of another valve', starting anytime on or before cohort entry
start date; allow events outside observation period.

\subsubsection{Cohort Exit}\label{cohort-exit-1}

The person also exists the cohort at the end of continuous observation.

\subsubsection{Cohort Eras}\label{cohort-eras-1}

Remaining events will be combined into cohort eras if they are within 0
days of each other.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{Transcatheter Aortic Valve Replacement (less than 80 yrs)
(Target, ATLAS ID:
901)}\label{transcatheter-aortic-valve-replacement-less-than-80-yrs-target-atlas-id-901}

\subsubsection{Cohort Entry Events}\label{cohort-entry-events-2}

People may enter the cohort when observing any of the following:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  condition occurrences of `{[}26HIRAMDV{]} Aortic Stenosis'.
\end{enumerate}

Limit cohort entry events to the earliest event per person.

Restrict entry events to having at least 1 device exposure of
`{[}26HIRAMDV{]} TAVR(total)', starting between 0 days before and all
days after cohort entry start date; allow events outside observation
period; starting on or after 1월 1, 2016.

\subsubsection{Additional Inclusion
Criteria}\label{additional-inclusion-criteria-2}

\paragraph*{I. aged more than 65}\label{i.-aged-more-than-65-1}
\addcontentsline{toc}{paragraph}{I. aged more than 65}

Entry events with the following event criteria: who are \textgreater= 65
years old. \#\#\#\# II. No high risk patient \{-\}

Entry events having no condition occurrences of `{[}26HIRAMDV{]} High
risk patient', starting anytime up to 7 days before cohort entry start
date; allow events outside observation period.

\paragraph*{III. No prior disorder of
heart}\label{iii.-no-prior-disorder-of-heart-1}
\addcontentsline{toc}{paragraph}{III. No prior disorder of heart}

Entry events having no condition occurrences of `{[}26HIRAMDV{]}
Disorder of another valve', starting anytime on or before cohort entry
start date; allow events outside observation period.

\subsubsection{Cohort Exit}\label{cohort-exit-2}

The person also exists the cohort at the end of continuous observation.

\subsubsection{Cohort Eras}\label{cohort-eras-2}

Remaining events will be combined into cohort eras if they are within 0
days of each other.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{Surgical Aortic Valve Replacement (less than 80 yrs)
(Comparator, ATLAS ID:
903)}\label{surgical-aortic-valve-replacement-less-than-80-yrs-comparator-atlas-id-903}

\subsubsection{Cohort Entry Events}\label{cohort-entry-events-3}

People may enter the cohort when observing any of the following:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  condition occurrences of `{[}26HIRAMDV{]} Aortic Stenosis'.
\end{enumerate}

Limit cohort entry events to the earliest event per person.

Restrict entry events to having at least 1 procedure occurrence of
`{[}26HIRAMDV{]} SAVR', starting between 0 days before and all days
after cohort entry start date; starting on or after 1월 1, 2016.

\subsubsection{Additional Inclusion
Criteria}\label{additional-inclusion-criteria-3}

\paragraph*{I. aged more than 18}\label{i.-aged-more-than-18-1}
\addcontentsline{toc}{paragraph}{I. aged more than 18}

Entry events with the following event criteria: who are \textgreater= 18
years old. \#\#\#\# II. No prior complex SAVR \{-\}

Entry events having no procedure occurrences of `{[}26HIRAMDV{]}
SAVR-complex surgery', starting anytime on or before cohort entry start
date; allow events outside observation period.

\paragraph*{III. No prior
sutureless,mechanical,TAVR}\label{iii.-no-prior-suturelessmechanicaltavr-1}
\addcontentsline{toc}{paragraph}{III. No prior
sutureless,mechanical,TAVR}

Entry events having no procedure occurrences of `{[}26HIRAMDV{]}
SAVR-sutureless,tavr,mechanical', starting anytime on or before cohort
entry start date; allow events outside observation period.

\paragraph*{IV. No prior
reintervention}\label{iv.-no-prior-reintervention-1}
\addcontentsline{toc}{paragraph}{IV. No prior reintervention}

Entry events having no procedure occurrences of `{[}26HIRAMDV{]}
SAVR-reintervention', starting anytime up to 7 days before cohort entry
start date; allow events outside observation period.

\paragraph*{V. No high risk patient}\label{v.-no-high-risk-patient-1}
\addcontentsline{toc}{paragraph}{V. No high risk patient}

Entry events having no condition occurrences of `{[}26HIRAMDV{]} High
risk patient', starting anytime up to 7 days before cohort entry start
date; allow events outside observation period.

\paragraph*{VI. No prior disorder of
heart}\label{vi.-no-prior-disorder-of-heart-1}
\addcontentsline{toc}{paragraph}{VI. No prior disorder of heart}

Entry events having no condition occurrences of `{[}26HIRAMDV{]}
Disorder of another valve', starting anytime on or before cohort entry
start date; allow events outside observation period.

\subsubsection{Cohort Exit}\label{cohort-exit-3}

The person also exists the cohort at the end of continuous observation.

\subsubsection{Cohort Eras}\label{cohort-eras-3}

Remaining events will be combined into cohort eras if they are within 0
days of each other.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{Transcatheter Aortic Valve Replacement-Medtronic (Target,
ATLAS ID:
904)}\label{transcatheter-aortic-valve-replacement-medtronic-target-atlas-id-904}

\subsubsection{Cohort Entry Events}\label{cohort-entry-events-4}

People may enter the cohort when observing any of the following:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  condition occurrences of `{[}26HIRAMDV{]} Aortic Stenosis'.
\end{enumerate}

Limit cohort entry events to the earliest event per person.

Restrict entry events to having at least 1 device exposure of any device
(including `{[}26HIRAMDV{]} TAVR (Medtronic)' source concepts), starting
between 0 days before and all days after cohort entry start date.

\subsubsection{Additional Inclusion
Criteria}\label{additional-inclusion-criteria-4}

\paragraph*{I. aged more than 18}\label{i.-aged-more-than-18-2}
\addcontentsline{toc}{paragraph}{I. aged more than 18}

Entry events with the following event criteria: who are \textgreater= 18
years old. \#\#\#\# II. No high risk patient \{-\}

Entry events having no condition occurrences of `{[}26HIRAMDV{]} High
risk patient', starting anytime up to 7 days before cohort entry start
date; allow events outside observation period.

\paragraph*{III. No prior disorder of
heart}\label{iii.-no-prior-disorder-of-heart-2}
\addcontentsline{toc}{paragraph}{III. No prior disorder of heart}

Entry events having at least 1 condition occurrence of `{[}26HIRAMDV{]}
Disorder of another valve', starting anytime on or before cohort entry
start date; allow events outside observation period.

\subsubsection{Cohort Exit}\label{cohort-exit-4}

The person also exists the cohort at the end of continuous observation.

\subsubsection{Cohort Eras}\label{cohort-eras-4}

Remaining events will be combined into cohort eras if they are within 0
days of each other.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{Transcatheter Aortic Valve Replacement-Medtronic (less than
80 yrs) (Target, ATLAS ID:
905)}\label{transcatheter-aortic-valve-replacement-medtronic-less-than-80-yrs-target-atlas-id-905}

\subsubsection{Cohort Entry Events}\label{cohort-entry-events-5}

People may enter the cohort when observing any of the following:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  condition occurrences of `{[}26HIRAMDV{]} Aortic Stenosis'.
\end{enumerate}

Limit cohort entry events to the earliest event per person.

Restrict entry events to having at least 1 device exposure of any device
(including `{[}26HIRAMDV{]} TAVR (Medtronic)' source concepts), starting
between 0 days before and all days after cohort entry start date.

\subsubsection{Additional Inclusion
Criteria}\label{additional-inclusion-criteria-5}

\paragraph*{I. aged more than 18}\label{i.-aged-more-than-18-3}
\addcontentsline{toc}{paragraph}{I. aged more than 18}

Entry events with the following event criteria: who are \textgreater= 18
years old. \#\#\#\# II. No high risk patient \{-\}

Entry events having no condition occurrences of `{[}26HIRAMDV{]} High
risk patient', starting anytime up to 7 days before cohort entry start
date; allow events outside observation period.

\paragraph*{III. No prior disorder of
heart}\label{iii.-no-prior-disorder-of-heart-3}
\addcontentsline{toc}{paragraph}{III. No prior disorder of heart}

Entry events having at least 1 condition occurrence of `{[}26HIRAMDV{]}
Disorder of another valve', starting anytime on or before cohort entry
start date; allow events outside observation period.

\subsubsection{Cohort Exit}\label{cohort-exit-5}

The person also exists the cohort at the end of continuous observation.

\subsubsection{Cohort Eras}\label{cohort-eras-5}

Remaining events will be combined into cohort eras if they are within 0
days of each other.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{Transcatheter Aortic Valve Replacement-Edwards (Target,
ATLAS ID:
906)}\label{transcatheter-aortic-valve-replacement-edwards-target-atlas-id-906}

\subsubsection{Cohort Entry Events}\label{cohort-entry-events-6}

People may enter the cohort when observing any of the following:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  condition occurrences of `{[}26HIRAMDV{]} Aortic Stenosis'.
\end{enumerate}

Limit cohort entry events to the earliest event per person.

Restrict entry events to having at least 1 device exposure of any device
(including `{[}26HIRAMDV{]} TAVR (Edwards)' source concepts), starting
between 0 days before and all days after cohort entry start date;
starting on or after 1월 1, 2016.

\subsubsection{Additional Inclusion
Criteria}\label{additional-inclusion-criteria-6}

\paragraph*{I. aged more than 18}\label{i.-aged-more-than-18-4}
\addcontentsline{toc}{paragraph}{I. aged more than 18}

Entry events with the following event criteria: who are \textgreater= 18
years old. \#\#\#\# II. No high risk patient \{-\}

Entry events having no condition occurrences of `{[}26HIRAMDV{]} High
risk patient', starting anytime up to 7 days before cohort entry start
date; allow events outside observation period.

\paragraph*{III. No prior disorder of
heart}\label{iii.-no-prior-disorder-of-heart-4}
\addcontentsline{toc}{paragraph}{III. No prior disorder of heart}

Entry events having no condition occurrences of `{[}26HIRAMDV{]}
Disorder of another valve', starting anytime on or before cohort entry
start date; allow events outside observation period.

\subsubsection{Cohort Exit}\label{cohort-exit-6}

The person also exists the cohort at the end of continuous observation.

\subsubsection{Cohort Eras}\label{cohort-eras-6}

Remaining events will be combined into cohort eras if they are within 0
days of each other.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{Transcatheter Aortic Valve Replacement-Edwards (less than 80
yrs) (Target, ATLAS ID:
907)}\label{transcatheter-aortic-valve-replacement-edwards-less-than-80-yrs-target-atlas-id-907}

\subsubsection{Cohort Entry Events}\label{cohort-entry-events-7}

People may enter the cohort when observing any of the following:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  condition occurrences of `{[}26HIRAMDV{]} Aortic Stenosis'.
\end{enumerate}

Limit cohort entry events to the earliest event per person.

Restrict entry events to having at least 1 device exposure of any device
(including `{[}26HIRAMDV{]} TAVR (Edwards)' source concepts), starting
between 0 days before and all days after cohort entry start date;
starting on or after 1월 1, 2016.

\subsubsection{Additional Inclusion
Criteria}\label{additional-inclusion-criteria-7}

\paragraph*{I. aged more than 18}\label{i.-aged-more-than-18-5}
\addcontentsline{toc}{paragraph}{I. aged more than 18}

Entry events with the following event criteria: who are \textgreater= 18
years old. \#\#\#\# II. No high risk patient \{-\}

Entry events having no condition occurrences of `{[}26HIRAMDV{]} High
risk patient', starting anytime up to 7 days before cohort entry start
date; allow events outside observation period.

\paragraph*{III. No prior disorder of
heart}\label{iii.-no-prior-disorder-of-heart-5}
\addcontentsline{toc}{paragraph}{III. No prior disorder of heart}

Entry events having no condition occurrences of `{[}26HIRAMDV{]}
Disorder of another valve', starting anytime on or before cohort entry
start date; allow events outside observation period.

\subsubsection{Cohort Exit}\label{cohort-exit-7}

The person also exists the cohort at the end of continuous observation.

\subsubsection{Cohort Eras}\label{cohort-eras-7}

Remaining events will be combined into cohort eras if they are within 0
days of each other.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Outcome Cohort Definitions}\label{outcome-cohort-definitions}

\subsection{Composite Outcomes All-cause mortality or disabling stroke
(ATLAS Cohort ID:
908)}\label{composite-outcomes-all-cause-mortality-or-disabling-stroke-atlas-cohort-id-908}

\subsubsection{Cohort Entry Events}\label{cohort-entry-events-8}

People may enter the cohort when observing any of the following:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  death of any form.
\item
  condition occurrences of `{[}26HIRAMDV{]} Stroke (SNOMED)'.
\item
  condition occurrences of any condition (including `{[}26HIRAMDV{]}
  Stroke (KCD)' source concepts).
\end{enumerate}

Restrict entry events to having at least 1 visit occurrence of
`{[}26HIRAMDV{]} Inpatient or ER visit', starting anytime on or before
cohort entry start date and ending between 0 days before and all days
after cohort entry start date.

\subsubsection{Cohort Exit}\label{cohort-exit-8}

The person also exists the cohort at the end of continuous observation.

\subsubsection{Cohort Eras}\label{cohort-eras-8}

Remaining events will be combined into cohort eras if they are within 0
days of each other.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{Reintervention (ATLAS Cohort ID:
909)}\label{reintervention-atlas-cohort-id-909}

\subsubsection{Cohort Entry Events}\label{cohort-entry-events-9}

People may enter the cohort when observing any of the following:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  device exposures of `{[}26HIRAMDV{]} TAVR (total)'.
\item
  procedure occurrences of `{[}26HIRAMDV{]} SAVR'.
\item
  procedure occurrences of `{[}26HIRAMDV{]} Valvuloplasty Aortic Valve'.
\item
  procedure occurrences of `{[}26HIRAMDV{]} TAVR (other approach,
  procedure)'.
\end{enumerate}

\subsubsection{Additional Inclusion
Criteria}\label{additional-inclusion-criteria-8}

\paragraph*{I. prior TAVR/SAVR}\label{i.-prior-tavrsavr}
\addcontentsline{toc}{paragraph}{I. prior TAVR/SAVR}

Entry events with any of the following criteria:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  having at least 1 device exposure of `{[}26HIRAMDV{]} TAVR (total)',
  starting anytime up to 365 days before cohort entry start date; allow
  events outside observation period.
\item
  having at least 1 procedure occurrence of `{[}26HIRAMDV{]} SAVR',
  starting anytime up to 365 days before cohort entry start date; allow
  events outside observation period.
\end{enumerate}

Limit qualifying entry events to the earliest event per person.

\subsubsection{Cohort Exit}\label{cohort-exit-9}

The person also exists the cohort at the end of continuous observation.

\subsubsection{Cohort Eras}\label{cohort-eras-9}

Remaining events will be combined into cohort eras if they are within 0
days of each other.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{Inpatient Stroke (ATLAS Cohort ID:
910)}\label{inpatient-stroke-atlas-cohort-id-910}

\subsubsection{Cohort Entry Events}\label{cohort-entry-events-10}

People may enter the cohort when observing any of the following:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  condition occurrences of `{[}26HIRAMDV{]} Stroke (SNOMED)'.
\item
  condition occurrences of any condition (including `{[}26HIRAMDV{]}
  Stroke (KCD)' source concepts).
\end{enumerate}

Restrict entry events to having at least 1 visit occurrence of
`{[}26HIRAMDV{]} Inpatient or ER visit', starting anytime on or before
cohort entry start date and ending between 0 days before and all days
after cohort entry start date.

\subsubsection{Cohort Exit}\label{cohort-exit-10}

The person also exists the cohort at the end of continuous observation.

\subsubsection{Cohort Eras}\label{cohort-eras-10}

Remaining events will be combined into cohort eras if they are within 0
days of each other.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{All Stroke (ATLAS Cohort ID:
911)}\label{all-stroke-atlas-cohort-id-911}

\subsubsection{Cohort Entry Events}\label{cohort-entry-events-11}

People enter the cohort when observing any of the following:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  condition occurrences of `{[}26HIRAMDV{]} Stroke (SNOMED)'.
\item
  condition occurrences of any condition (including `{[}26HIRAMDV{]}
  Stroke (KCD)' source concepts).
\end{enumerate}

\subsubsection{Cohort Exit}\label{cohort-exit-11}

The person also exists the cohort at the end of continuous observation.

\subsubsection{Cohort Eras}\label{cohort-eras-11}

Remaining events will be combined into cohort eras if they are within 0
days of each other.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{Aortic valve hospitalization (ATLAS Cohort ID:
912)}\label{aortic-valve-hospitalization-atlas-cohort-id-912}

\subsubsection{Cohort Entry Events}\label{cohort-entry-events-12}

People may enter the cohort when observing any of the following:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  condition occurrences of `{[}26HIRAMDV{]} aortic valve
  hospitalization'.
\end{enumerate}

Restrict entry events to having at least 1 visit occurrence of
`{[}26HIRAMDV{]} Inpatient or ER visit', starting anytime on or before
cohort entry start date and ending between 0 days before and all days
after cohort entry start date.

\subsubsection{Cohort Exit}\label{cohort-exit-12}

The person also exists the cohort at the end of continuous observation.

\subsubsection{Cohort Eras}\label{cohort-eras-12}

Remaining events will be combined into cohort eras if they are within 0
days of each other.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{Composite Outcomes All-cause mortality or disabling stroke
or aortic valve hospitalization (ATLAS Cohort ID:
913)}\label{composite-outcomes-all-cause-mortality-or-disabling-stroke-or-aortic-valve-hospitalization-atlas-cohort-id-913}

\subsubsection{Cohort Entry Events}\label{cohort-entry-events-13}

People may enter the cohort when observing any of the following:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  death of any form.
\item
  condition occurrences of `{[}26HIRAMDV{]} Stroke (SNOMED)'.
\item
  condition occurrences of `{[}26HIRAMDV{]} aortic valve
  hospitalization'.
\end{enumerate}

Restrict entry events to having at least 1 visit occurrence of
`{[}26HIRAMDV{]} Inpatient or ER visit', starting anytime on or before
cohort entry start date and ending between 0 days before and all days
after cohort entry start date.

\subsubsection{Cohort Exit}\label{cohort-exit-13}

The person also exists the cohort at the end of continuous observation.

\subsubsection{Cohort Eras}\label{cohort-eras-13}

Remaining events will be combined into cohort eras if they are within 0
days of each other.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{New PPI (ATLAS Cohort ID:
914)}\label{new-ppi-atlas-cohort-id-914}

\subsubsection{Cohort Entry Events}\label{cohort-entry-events-14}

People may enter the cohort when observing any of the following:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  procedure occurrences of `{[}26HIRAMDV{]} Permanent pacemaker
  implant'.
\end{enumerate}

Limit cohort entry events to the earliest event per person.

\subsubsection{Additional Inclusion
Criteria}\label{additional-inclusion-criteria-9}

\paragraph*{I. exclude prior PPI}\label{i.-exclude-prior-ppi}
\addcontentsline{toc}{paragraph}{I. exclude prior PPI}

Entry events with any of the following criteria:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  having no procedure occurrences of `{[}26HIRAMDV{]} Removal of
  permanent pacemaker implant', starting anytime prior to cohort entry
  start date; allow events outside observation period.
\item
  having no procedure occurrences of `{[}26HIRAMDV{]} Permanent
  pacemaker implant', starting anytime prior to cohort entry start date;
  allow events outside observation period.
\end{enumerate}

\subsubsection{Cohort Exit}\label{cohort-exit-14}

The person also exists the cohort at the end of continuous observation.

\subsubsection{Cohort Eras}\label{cohort-eras-14}

Remaining events will be combined into cohort eras if they are within 0
days of each other.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{Atrial\_fibrillation (ATLAS Cohort ID:
915)}\label{atrial_fibrillation-atlas-cohort-id-915}

\subsubsection{Cohort Entry Events}\label{cohort-entry-events-15}

People enter the cohort when observing any of the following:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  condition occurrences of `{[}26HIRAMDV{]} Atrial fibrillation'.
\end{enumerate}

\subsubsection{Cohort Exit}\label{cohort-exit-15}

The person also exists the cohort at the end of continuous observation.

\subsubsection{Cohort Eras}\label{cohort-eras-15}

Remaining events will be combined into cohort eras if they are within 0
days of each other.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{All-cause mortality (ATLAS Cohort ID:
916)}\label{all-cause-mortality-atlas-cohort-id-916}

\subsubsection{Cohort Entry Events}\label{cohort-entry-events-16}

People enter the cohort when observing any of the following:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  death of any form.
\end{enumerate}

Limit cohort entry events to the earliest event per person.

\subsubsection{Cohort Exit}\label{cohort-exit-16}

The person also exists the cohort at the end of continuous observation.

\subsubsection{Cohort Eras}\label{cohort-eras-16}

Remaining events will be combined into cohort eras if they are within 0
days of each other.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{Myocardial infarction (ATLAS Cohort ID:
917)}\label{myocardial-infarction-atlas-cohort-id-917}

\subsubsection{Cohort Entry Events}\label{cohort-entry-events-17}

People enter the cohort when observing any of the following:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  condition occurrences of `{[}26HIRAMDV{]} Myocardial infarction
  (SNOMED)'.
\item
  condition occurrences of any condition (including `{[}26HIRAMDV{]}
  Myocardial infarction (KCD)' source concepts).
\end{enumerate}

\subsubsection{Cohort Exit}\label{cohort-exit-17}

The person also exists the cohort at the end of continuous observation.

\subsubsection{Cohort Eras}\label{cohort-eras-17}

Remaining events will be combined into cohort eras if they are within 0
days of each other.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\end{document}
